"""
Polymarket 全景监控 — 分类体系与关键词配置
精准关键词避免体育/娱乐噪音污染
"""

CATEGORIES = [
    # ─── 宏观 ────────────────────────────────────────────────────────────────
    {
        "id": "us_recession",
        "label": "美国衰退概率",
        "category": "macro",
        "subcategory": "经济周期",
        "keywords": ["US recession 2025", "US recession 2026", "recession probability"],
        "description": "市场对美国经济进入技术性衰退的概率押注",
        "icon": "📉",
    },
    {
        "id": "fed_rate_cut",
        "label": "美联储降息",
        "category": "macro",
        "subcategory": "货币政策",
        "keywords": ["Fed rate cut 2025", "Federal Reserve cut 2025", "Fed cut September 2025"],
        "description": "美联储当年降息次数/时间押注",
        "icon": "🏦",
    },
    {
        "id": "fed_rate_hike",
        "label": "美联储加息",
        "category": "macro",
        "subcategory": "货币政策",
        "keywords": ["Fed rate hike 2025", "Federal Reserve hike rate 2025"],
        "description": "美联储加息概率押注",
        "icon": "🏦",
    },
    {
        "id": "fed_funds_rate",
        "label": "联邦基金利率目标",
        "category": "macro",
        "subcategory": "货币政策",
        "keywords": ["federal funds rate end 2025", "FOMC rate decision 2025", "interest rate year end"],
        "description": "年末联邦基金利率水平押注",
        "icon": "🏦",
    },
    {
        "id": "cpi_inflation",
        "label": "CPI / 通胀",
        "category": "macro",
        "subcategory": "通胀",
        "keywords": ["CPI inflation 2025", "inflation above 3% 2025", "CPI year end 2025"],
        "description": "CPI 走向及通胀超预期/不及预期押注",
        "icon": "📊",
    },
    {
        "id": "nasdaq_level",
        "label": "纳斯达克指数",
        "category": "macro",
        "subcategory": "股市指数",
        "keywords": ["Nasdaq 20000 2025", "Nasdaq end of year 2025", "Nasdaq 18000"],
        "description": "纳斯达克年末/季末区间押注",
        "icon": "📈",
    },
    {
        "id": "sp500_level",
        "label": "标普500指数",
        "category": "macro",
        "subcategory": "股市指数",
        "keywords": ["S&P 500 end of 2025", "SPX 6000 2025", "S&P 500 year end 2025"],
        "description": "标普500年末/季末区间押注",
        "icon": "📈",
    },
    {
        "id": "btc_price",
        "label": "比特币价格",
        "category": "macro",
        "subcategory": "加密货币",
        "keywords": ["Bitcoin price end 2025", "BTC 100000", "Bitcoin 200000"],
        "description": "比特币价格区间押注（风险偏好指标）",
        "icon": "₿",
    },
    {
        "id": "us_china_trade",
        "label": "中美贸易/关税",
        "category": "macro",
        "subcategory": "地缘政治",
        "keywords": ["US China tariff 2025", "China tariff rate 2025", "US China trade deal 2025"],
        "description": "中美关税/贸易摩擦走向押注",
        "icon": "🌐",
    },
    {
        "id": "us_debt_fiscal",
        "label": "美国债务/财政",
        "category": "macro",
        "subcategory": "财政",
        "keywords": ["US debt ceiling 2025", "US government shutdown 2025", "US budget deficit"],
        "description": "美国债务上限/政府停摆押注",
        "icon": "💵",
    },
    {
        "id": "usd_strength",
        "label": "美元强弱",
        "category": "macro",
        "subcategory": "汇率",
        "keywords": ["dollar index 2025 end", "DXY 2025", "USD versus EUR 2025"],
        "description": "美元指数走向押注",
        "icon": "💱",
    },
    {
        "id": "geopolitics",
        "label": "地缘政治风险",
        "category": "macro",
        "subcategory": "地缘政治",
        "keywords": ["Ukraine ceasefire 2025", "Taiwan conflict 2025", "Iran nuclear deal 2025"],
        "description": "重大地缘政治冲突升降级押注",
        "icon": "🌍",
    },

    # ─── 行业 ────────────────────────────────────────────────────────────────
    {
        "id": "sector_ai",
        "label": "AI 行业",
        "category": "sector",
        "subcategory": "AI/科技",
        "keywords": ["GPT-5 release", "OpenAI 2025", "AI regulation 2025", "Claude 4"],
        "description": "AI 模型发布、监管、能力里程碑押注",
        "icon": "🤖",
    },
    {
        "id": "sector_nvidia",
        "label": "英伟达 (NVDA)",
        "category": "sector",
        "subcategory": "AI/科技",
        "keywords": ["Nvidia earnings 2025", "NVDA stock 2025", "Nvidia revenue"],
        "description": "英伟达财报 beat/miss、股价区间押注",
        "icon": "🎮",
    },
    {
        "id": "sector_semiconductor",
        "label": "半导体行业",
        "category": "sector",
        "subcategory": "半导体",
        "keywords": ["semiconductor export 2025", "TSMC earnings 2025", "chip ban 2025"],
        "description": "半导体供需、制裁、产能押注",
        "icon": "💾",
    },
    {
        "id": "sector_mag7",
        "label": "Mag7 科技巨头",
        "category": "sector",
        "subcategory": "互联网平台",
        "keywords": ["Apple earnings 2025", "Google earnings 2025", "Microsoft earnings 2025"],
        "description": "Mag7 财报 beat/miss 押注",
        "icon": "🍎",
    },
    {
        "id": "sector_crypto_reg",
        "label": "加密/Web3",
        "category": "sector",
        "subcategory": "加密货币",
        "keywords": ["crypto regulation 2025", "Ethereum ETF 2025", "stablecoin bill 2025"],
        "description": "加密货币监管、ETF、协议升级押注",
        "icon": "🔐",
    },
    {
        "id": "sector_ev",
        "label": "电动车行业",
        "category": "sector",
        "subcategory": "新能源",
        "keywords": ["Tesla earnings 2025", "Tesla deliveries 2025", "EV sales 2025"],
        "description": "EV 交付量、政策补贴、竞争格局押注",
        "icon": "⚡",
    },
    {
        "id": "sector_energy",
        "label": "能源/石油",
        "category": "sector",
        "subcategory": "能源",
        "keywords": ["oil price 2025 end", "OPEC production 2025", "crude oil 2025"],
        "description": "油价、OPEC 产量、能源政策押注",
        "icon": "🛢️",
    },
    {
        "id": "sector_pharma",
        "label": "医药/生物科技",
        "category": "sector",
        "subcategory": "医药",
        "keywords": ["FDA approval 2025", "GLP-1 2025", "biotech IPO 2025", "Ozempic 2025"],
        "description": "FDA 批准、新药里程碑、GLP-1 押注",
        "icon": "💊",
    },
    {
        "id": "sector_china_stocks",
        "label": "中概/A股",
        "category": "sector",
        "subcategory": "中国资产",
        "keywords": ["China economy 2025", "China stock market 2025", "Alibaba earnings 2025"],
        "description": "中概股政策、财报、中国经济押注",
        "icon": "🇨🇳",
    },
    {
        "id": "sector_ipo",
        "label": "IPO 市场",
        "category": "sector",
        "subcategory": "一级市场",
        "keywords": ["IPO listing 2025", "public offering 2025", "Klarna IPO", "SpaceX IPO"],
        "description": "重大 IPO 定价、上市时间押注",
        "icon": "🚀",
    },
    {
        "id": "sector_fintech",
        "label": "金融/银行",
        "category": "sector",
        "subcategory": "金融",
        "keywords": ["bank earnings 2025", "financial regulation 2025", "JPMorgan earnings"],
        "description": "银行财报、金融监管押注",
        "icon": "🏛️",
    },
]

# 快速查找索引
CATEGORY_MAP = {c["id"]: c for c in CATEGORIES}
MACRO_IDS    = [c["id"] for c in CATEGORIES if c["category"] == "macro"]
SECTOR_IDS   = [c["id"] for c in CATEGORIES if c["category"] == "sector"]
